# Generated by Django 2.2 on 2023-01-12 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20230112_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankjournal',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_champion', to=settings.AUTH_USER_MODEL, verbose_name='Champion'),
        ),
        migrations.AlterField(
            model_name='receivedjournal',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rcv_champion', to=settings.AUTH_USER_MODEL, verbose_name='Champion'),
        ),
    ]
