# Generated by Django 2.2 on 2023-01-12 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20230112_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('amount', models.FloatField()),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('cr_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acc06', to='account.Account', verbose_name='Cr account')),
                ('dr_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accr', to='account.Account', verbose_name='Dr Account')),
            ],
        ),
    ]
