# Generated by Django 2.2 on 2023-01-13 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0009_auto_20230113_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Madeni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('desc', models.TextField()),
                ('is_paid', models.BooleanField(default=False, verbose_name='Ameshalipa')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('desc_payment', models.TextField(null=True, verbose_name='Payment description')),
                ('date', models.DateField()),
                ('champion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='madeni_champion', to=settings.AUTH_USER_MODEL, verbose_name='Champion')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
