# Generated by Django 2.2 on 2023-02-04 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0010_madeni'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeBorrowed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True, null=True)),
                ('desc', models.TextField()),
                ('is_paid', models.BooleanField(default=False, verbose_name='Tumeshalipa')),
                ('amount', models.FloatField(blank=True, null=True)),
                ('desc_payment', models.TextField(null=True, verbose_name='Payment description')),
                ('date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='expensejournal',
            name='borrowed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Borrowed', to='account.WeBorrowed', verbose_name='Borrowed Amount'),
        ),
    ]
