# Generated by Django 2.2 on 2023-02-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20230204_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='weborrowed',
            name='loanee',
            field=models.CharField(max_length=300, null=True, verbose_name='The Giver'),
        ),
    ]
