# Generated by Django 2.2 on 2020-11-30 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(max_length=400)),
                ('tender_no', models.CharField(max_length=300, null=True)),
                ('company', models.CharField(max_length=300)),
                ('amount', models.FloatField()),
                ('company_type', models.CharField(choices=[('Government', 'Government'), ('Private', 'Private')], max_length=500)),
                ('status', models.CharField(choices=[('Evaluation', 'Evaluation'), ('Worn', 'Worn'), ('Failed', 'Failed')], max_length=500)),
                ('submission_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
