# Generated by Django 2.2 on 2023-01-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_payment_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.IntegerField(null=True, verbose_name='TYPE+1-Expense, 2-Account Transfer, 3-Sales,4-other receivings'),
        ),
    ]
