# Generated by Django 2.2 on 2023-01-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='trans_account_cr_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='trans_account_dr_id',
            field=models.IntegerField(null=True),
        ),
    ]
