# Generated by Django 2.2 on 2020-11-17 10:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=300, null=True)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200, null=True)),
                ('active_status', models.NullBooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(default='None', max_length=30, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('mobile_two', models.CharField(blank='', default='', max_length=20, null=True)),
                ('date_added', models.DateTimeField(blank='', default=datetime.datetime(2020, 11, 17, 13, 52, 29, 292195), null=True)),
                ('has_a_company', models.BooleanField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Company')),
            ],
        ),
    ]
