# Generated by Django 2.0.6 on 2018-06-15 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(blank='', default=datetime.datetime(2018, 6, 15, 12, 34, 58, 556541), null=True),
        ),
    ]
