# Generated by Django 2.2 on 2020-11-17 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_company_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='city',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.CharField(default='None', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(blank='', default=datetime.datetime(2020, 11, 17, 15, 12, 5, 243844), null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='has_a_company',
            field=models.BooleanField(default=False),
        ),
    ]
