# Generated by Django 2.0.6 on 2018-06-16 17:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20180615_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(blank='', default=datetime.datetime(2018, 6, 16, 20, 6, 13, 254933), null=True),
        ),
    ]
