# Generated by Django 2.0.1 on 2018-06-23 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20180623_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(blank='', default=datetime.datetime(2018, 6, 23, 12, 25, 5, 949786), null=True),
        ),
    ]
