# Generated by Django 2.2 on 2020-11-19 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20201119_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(blank='', default=datetime.datetime(2020, 11, 19, 17, 4, 12, 921069), null=True),
        ),
    ]
