# Generated by Django 2.0.1 on 2018-07-18 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20180718_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(blank='', default=datetime.datetime(2018, 7, 18, 19, 51, 12, 832025), null=True),
        ),
    ]
