# Generated by Django 2.2 on 2020-11-20 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0008_auto_20201119_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(blank='', default=datetime.datetime(2020, 11, 20, 5, 44, 25, 768740), null=True),
        ),
    ]
