# Generated by Django 2.0.1 on 2018-07-18 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_auto_20180718_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(blank='', default=datetime.datetime(2018, 7, 18, 20, 1, 0, 244199), null=True),
        ),
    ]
