# Generated by Django 2.2 on 2020-11-24 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0011_auto_20201120_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(blank='', default=datetime.datetime(2020, 11, 24, 16, 53, 9, 310403), null=True),
        ),
    ]
