# Generated by Django 2.2 on 2020-12-02 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_auto_20201202_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(blank='', default=datetime.datetime(2020, 12, 2, 15, 13, 1, 154475), null=True),
        ),
    ]
