# Generated by Django 2.2 on 2020-12-03 09:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0014_auto_20201202_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(blank='', default=datetime.datetime(2020, 12, 3, 12, 29, 51, 135553), null=True),
        ),
    ]
