# Generated by Django 2.2 on 2020-12-08 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0015_auto_20201203_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(blank='', default=datetime.datetime(2020, 12, 8, 15, 20, 57, 429999), null=True),
        ),
    ]
