# Generated by Django 2.2 on 2020-12-15 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0019_auto_20201211_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(blank='', default=datetime.datetime(2020, 12, 15, 19, 54, 22, 152951), null=True),
        ),
    ]
