# Generated by Django 2.2 on 2020-12-17 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0020_auto_20201215_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(blank='', default=datetime.datetime(2020, 12, 17, 16, 0, 37, 652346), null=True),
        ),
    ]
