# Generated by Django 2.2 on 2021-01-11 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0021_auto_20201217_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(blank='', default=datetime.datetime(2021, 1, 11, 12, 22, 40, 998998), null=True),
        ),
    ]
