# Generated by Django 2.2 on 2021-01-20 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0022_auto_20210111_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(blank='', default=datetime.datetime(2021, 1, 20, 20, 1, 35, 63551), null=True),
        ),
    ]
