# Generated by Django 2.2 on 2021-02-19 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0025_auto_20210121_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(blank='', default=datetime.datetime(2021, 2, 19, 13, 45, 57, 411819), null=True),
        ),
    ]
