# Generated by Django 2.2 on 2021-02-19 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0027_auto_20210219_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(blank='', default=datetime.datetime(2021, 2, 19, 14, 12, 55, 371828), null=True),
        ),
    ]
