# Generated by Django 2.2 on 2021-04-21 10:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0031_auto_20210305_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(blank='', default=datetime.datetime(2021, 4, 21, 13, 42, 21, 854046), null=True),
        ),
    ]
