# Generated by Django 2.2 on 2021-04-21 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0032_auto_20210421_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(blank='', default=datetime.datetime(2021, 4, 21, 14, 3, 59, 155313), null=True),
        ),
    ]
