# Generated by Django 2.2 on 2021-04-21 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0033_auto_20210421_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(blank='', default=datetime.datetime(2021, 4, 21, 14, 4, 15, 284357), null=True),
        ),
    ]
