# Generated by Django 2.2 on 2021-05-08 09:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0034_auto_20210421_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(blank='', default=datetime.datetime(2021, 5, 8, 12, 5, 30, 187161), null=True),
        ),
    ]
