# Generated by Django 2.2 on 2021-06-29 10:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0035_auto_20210508_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(blank='', default=datetime.datetime(2021, 6, 29, 13, 26, 39, 257169), null=True),
        ),
    ]
