# Generated by Django 2.2 on 2021-07-05 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0036_auto_20210629_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(blank='', default=datetime.datetime(2021, 7, 5, 18, 31, 9, 819384), null=True),
        ),
    ]
