# Generated by Django 2.2 on 2021-07-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0037_auto_20210705_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
