# Generated by Django 2.2 on 2020-11-30 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=400)),
                ('desc', models.TextField(max_length=400)),
                ('company', models.CharField(max_length=300)),
                ('amount', models.FloatField()),
                ('company_type', models.CharField(choices=[('Government', 'Government'), ('Private', 'Private')], max_length=500)),
                ('status', models.CharField(choices=[('Onprogress', 'Onprogress'), ('Completed', 'Completed'), ('Pending', 'Pending')], max_length=500)),
                ('start_date', models.DateTimeField(null=True)),
                ('end_date', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=400)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_proj', to='project.Project')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_responsible', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectAmounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_name', models.TextField(max_length=400)),
                ('amount', models.FloatField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_amount', to='project.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amount_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
