# Generated by Django 2.2 on 2021-02-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_projecttasks_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttasks',
            name='status',
            field=models.CharField(max_length=20, null=True, verbose_name='Status'),
        ),
    ]
