# Generated by Django 2.0.6 on 2018-06-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lead', '0003_auto_20180616_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('agenda', models.CharField(max_length=300)),
                ('desc', models.CharField(max_length=500, null=True)),
                ('next_meeting_date', models.DateTimeField(null=True)),
                ('next_agenda', models.CharField(max_length=300, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.Lead')),
            ],
        ),
    ]
