# Generated by Django 2.2 on 2020-11-17 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('meeting_time', models.TimeField(blank=True, null=True)),
                ('agenda', models.CharField(max_length=300)),
                ('desc', models.CharField(max_length=500, null=True)),
                ('meeting_status', models.CharField(default='scheduled', max_length=10, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.Lead')),
            ],
        ),
    ]
