# Generated by Django 2.0.1 on 2018-07-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='next_agenda',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='next_meeting_date',
        ),
        migrations.AddField(
            model_name='meeting',
            name='meeting_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
