# Generated by Django 2.0.1 on 2018-07-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_auto_20180718_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='meeting_status',
            field=models.CharField(default='scheduled', max_length=10, null=True),
        ),
    ]
