# Generated by Django 2.0.6 on 2018-06-15 08:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('desc', models.TextField(max_length=400)),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2018, 6, 15, 11, 25, 56, 781501))),
                ('expected_sale_amount', models.FloatField()),
                ('expected_closing_date', models.DateTimeField(null=True)),
                ('status_desc', models.CharField(max_length=50, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Lead_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lead.Lead_status'),
        ),
        migrations.AddField(
            model_name='lead',
            name='user',
            field=models.ForeignKey(on_delete='CASECADE', to=settings.AUTH_USER_MODEL),
        ),
    ]
