# Generated by Django 2.2 on 2020-11-17 10:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('desc', models.TextField(max_length=400)),
                ('reg_date', models.DateTimeField(default=datetime.datetime(2020, 11, 17, 13, 52, 29, 293195))),
                ('expected_sale_amount', models.FloatField()),
                ('expected_closing_date', models.DateTimeField(null=True)),
                ('status_desc', models.CharField(max_length=50, null=True)),
                ('score', models.IntegerField(blank=True, default=10, null=True)),
                ('status_info', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 11, 17, 13, 52, 29, 294193))),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Contact')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lead.Lead_status')),
            ],
        ),
    ]
