# Generated by Django 2.0.1 on 2018-06-23 09:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_auto_20180623_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 6, 23, 12, 25, 5, 955785)),
        ),
        migrations.AlterField(
            model_name='lead',
            name='score',
            field=models.IntegerField(blank=True, default=10, max_length=20, null=True),
        ),
    ]
