# Generated by Django 2.0.1 on 2018-07-18 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0007_auto_20180718_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 18, 19, 37, 57, 26621)),
        ),
    ]
