# Generated by Django 2.0.1 on 2018-07-18 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0009_auto_20180718_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 18, 20, 1, 0, 259825)),
        ),
    ]
