# Generated by Django 2.2 on 2020-12-08 12:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0015_auto_20201203_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetcontact',
            name='next_follup_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='targetcontact',
            name='visit_desc',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 15, 20, 57, 433332)),
        ),
        migrations.AlterField(
            model_name='lead',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 15, 20, 57, 432980)),
        ),
    ]
