# Generated by Django 2.2 on 2020-12-08 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0016_auto_20201208_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetcontact',
            name='status',
            field=models.CharField(choices=[('contact', 'Contact'), ('finding', 'Finding'), ('dropped', 'Dropped')], default='finding', max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 15, 36, 14, 173772)),
        ),
        migrations.AlterField(
            model_name='lead',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 15, 36, 14, 172396)),
        ),
    ]
