# Generated by Django 2.2 on 2020-12-08 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0017_auto_20201208_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetcontact',
            name='contact_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 15, 39, 18, 349418)),
        ),
        migrations.AlterField(
            model_name='lead',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 8, 15, 39, 18, 348878)),
        ),
        migrations.AlterField(
            model_name='targetcontact',
            name='status',
            field=models.CharField(choices=[('', '-------------'), ('contact', 'Contact'), ('finding', 'Finding'), ('dropped', 'Dropped')], default='finding', max_length=30),
        ),
    ]
