# Generated by Django 2.2 on 2021-07-05 15:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0037_auto_20210705_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 18, 33, 34, 154448)),
        ),
        migrations.AlterField(
            model_name='lead',
            name='reg_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 5, 18, 33, 34, 154448)),
        ),
    ]
