# Generated by Django 2.2 on 2021-08-12 09:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0040_leadactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='targetcontact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
