# Generated by Django 2.2 on 2023-01-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perm_name', models.CharField(max_length=300, verbose_name='Permission name')),
                ('perm_desc', models.CharField(max_length=200, verbose_name='Description')),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='perm',
            field=models.ManyToManyField(to='user.CustPermission'),
        ),
    ]
