# Generated by Django 2.2 on 2020-11-19 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0006_auto_20201119_1704'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=50, verbose_name='Invoice No')),
                ('invoice_date', models.DateField(verbose_name='Invoice Date')),
                ('invoice_status', models.CharField(choices=[('QOUTE', 'QOUTATION'), ('INVOICE', 'INVOICE')], max_length=300)),
                ('currency', models.CharField(default='TZS', max_length=500)),
                ('start_date', models.DateField(null=True, verbose_name='Invoice Start date')),
                ('end_date', models.DateField(null=True, verbose_name='Invoice Start date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contact.Contact', verbose_name='Contact/Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=200, verbose_name='Description')),
                ('qty', models.FloatField(max_length=40, verbose_name='Quantity')),
                ('price', models.FloatField(max_length=40, verbose_name='Price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='invoice.Invoice')),
            ],
        ),
    ]
