# Generated by Django 2.2 on 2020-11-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='antetion_person',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='city',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='company',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pobox',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
