# Generated by Django 2.2 on 2020-11-19 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_auto_20201119_1726'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='contact',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='currency',
            field=models.CharField(choices=[('TZS', 'TZS'), ('USD', 'USD')], default='TZS', max_length=500),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Invoice End date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(auto_now_add=True, verbose_name='Invoice Date'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.CharField(max_length=50, null=True, verbose_name='Invoice No'),
        ),
    ]
