# Generated by Django 2.2 on 2020-11-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_auto_20201119_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_aninvoice',
            field=models.BooleanField(default=False),
        ),
    ]
