# Generated by Django 2.2 on 2020-11-20 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_is_aninvoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_start_date',
            field=models.DateField(null=True, verbose_name='Invoice Date'),
        ),
    ]
