# Generated by Django 2.2 on 2020-11-20 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_invoice_invoice_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
