# Generated by Django 2.2 on 2020-11-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_invoice_is_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='no',
            field=models.IntegerField(default=1),
        ),
    ]
