# Generated by Django 2.2 on 2021-01-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_invoice_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='file',
        ),
    ]
