# Generated by Django 2.2 on 2021-04-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0015_invoice_deposittype'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='stock_ifo',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
