# Generated by Django 2.2 on 2021-04-21 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0016_invoice_stock_ifo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='stock_ifo',
            new_name='stock_info',
        ),
    ]
