# Generated by Django 2.2 on 2021-05-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0017_auto_20210421_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tag',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
