# Generated by Django 2.2 on 2021-07-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0020_jobcard_jobcardline'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='status',
            field=models.CharField(default='done', max_length=20, verbose_name='Status'),
        ),
    ]
