# Generated by Django 2.2 on 2021-07-05 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0021_jobcard_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcardline',
            name='device',
        ),
    ]
