# Generated by Django 2.2 on 2021-07-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0022_remove_jobcardline_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcardline',
            name='desc',
            field=models.TextField(max_length=200, verbose_name='Description'),
        ),
    ]
