# Generated by Django 2.2 on 2022-11-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0023_auto_20210705_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='desc',
            field=models.TextField(max_length=200, verbose_name='Description'),
        ),
    ]
