# Generated by Django 2.2 on 2022-11-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0024_auto_20221108_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='show_tax',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='desc',
            field=models.TextField(max_length=2000, verbose_name='Description'),
        ),
    ]
