# Generated by Django 2.2 on 2023-01-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0025_auto_20221129_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='comment',
            field=models.TextField(max_length=500, null=True, verbose_name='Comments descriptions, also state payment history'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='show_tax',
            field=models.BooleanField(default=True, verbose_name='Inclued VAT'),
        ),
    ]
