# Generated by Django 2.2 on 2023-01-11 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0027_auto_20230111_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=100, verbose_name='Description')),
                ('expected_amount', models.FloatField(max_length=40, null=True, verbose_name='Amount expected to be given')),
                ('actual_amount', models.FloatField(max_length=40, null=True, verbose_name='Amount expected to be given')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoiceiddist', to='invoice.Invoice')),
            ],
        ),
    ]
