# Generated by Django 2.2 on 2023-01-12 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice', '0029_auto_20230111_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedistribution',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='createdby009', to=settings.AUTH_USER_MODEL),
        ),
    ]
