# Generated by Django 2.2 on 2023-04-11 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0030_invoicedistribution_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='paid',
            field=models.FloatField(max_length=40, null=True, verbose_name='Paid Amount'),
        ),
    ]
