# Generated by Django 2.2 on 2023-01-12 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankjournal',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank2journal', to='account.Account', verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='expensejournal',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account2journal', to='account.Account', verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='journal',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal', to='account.Account', verbose_name='Account'),
        ),
        migrations.AddField(
            model_name='receivedjournal',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_payment', to='account.Account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='expensejournal',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ex_champion', to=settings.AUTH_USER_MODEL, verbose_name='Champion'),
        ),
    ]
